---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-helm
spec:
  ignoreCrossplaneConstraints: false
  package: crossplane/provider-helm:v0.9.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false