---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: default-app
  namespace: argocd
spec:
  timeout: 2m
  path: "./default/"
  interval: 5m
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: argo-flux-demo
    namespace: flux-system
  dependsOn:
  - name: argo-flux-installation
