---
apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  timeout: 2m
  path: "./crossplane/"
  interval: 5m
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: argo-flux-demo
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane-provider-aws
  namespace: crossplane-system
spec:
  timeout: 2m
  path: "./crossplane-provider-aws/"
  interval: 5m
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: argo-flux-demo
    namespace: flux-system
